# Generated by Django 4.0.3 on 2022-05-21 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0002_category_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
