# Generated by Django 4.0.3 on 2022-05-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_post_modify_date_post_user_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dicount_price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
