# Generated by Django 4.0.3 on 2022-05-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0005_post_dicount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recuit_num',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
