# Generated by Django 4.0.3 on 2022-05-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_post_recuit_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='participants',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
