# Generated by Django 4.0.3 on 2022-05-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_post_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='recuit_num',
            new_name='recruit_num',
        ),
    ]
