# Generated by Django 4.0.3 on 2022-05-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0008_rename_recuit_num_post_recruit_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
    ]
