# Generated by Django 4.0.3 on 2022-05-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0010_post_joined_users_alter_post_image'),
        ('pybo', '0013_alter_post_image'),
    ]

    operations = [
    ]
