# Generated by Django 4.0.3 on 2022-05-25 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0014_merge_20220526_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='joined_users',
            field=models.ManyToManyField(blank=True, related_name='joined_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
