# Generated by Django 4.0.3 on 2022-05-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0020_alter_post_like_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
